/**
 * Assembly wrapper generator (plan D).
 *
 * Turns a validated `{ component, props }` selection into a thin
 * Component.tsx that forwards every AnimationProps field BY NAME to the
 * prefab library component, with the spec inlined as a typed const.
 *
 * Hard constraints baked into the template (do not relax — two review
 * rounds pinned these down):
 *
 *   - Named forwarding, never `{...props}`: the narration-sync contract
 *     check (`checkNarrationSyncContract`, src/ai/visual-metrics.ts) only
 *     regex-scans the source for `\blineTimings\b`, and the safe-bottom
 *     scan (`scanSafeBottomUsage`, src/ai/validate.ts) requires
 *     `subtitleSafeBottom` to appear in a value position. A spread would
 *     pass tsc but fail both static gates.
 *   - The spec is inlined via `JSON.stringify` (escaping is stringify's
 *     job) and annotated with the real `XxxSpec` type from the library
 *     barrel, so the pipeline's tsc pass re-checks the LLM's JSON against
 *     the component's actual props on every build.
 *   - Value imports use the extensionless relative specifier
 *     `../../../remotion/library` — the Remotion webpack config has no
 *     extensionAlias, so a `.js` suffix would fail to resolve at bundle
 *     time (same convention as remotion/VideoComposition.tsx).
 *   - `export default` is required by astStaticScan consumers.
 */

import { registeredComponentNames } from "./visual-registry.js";

/** Component names are spliced into generated source — keep them identifier-safe. */
const COMPONENT_NAME_RE = /^[A-Z][A-Za-z0-9]*$/;

/**
 * Build the wrapper Component.tsx source for a validated assembly selection.
 *
 * @param componentName Registered library component (e.g. "KeyPoints").
 * @param spec          Zod-validated spec (pure JSON data).
 * @throws if the name is not identifier-safe or the spec is not
 *         JSON-serializable (undefined / functions only).
 */
export function buildAssemblyWrapper(componentName: string, spec: unknown): string {
  if (!COMPONENT_NAME_RE.test(componentName)) {
    throw new Error(
      `buildAssemblyWrapper: invalid component name ${JSON.stringify(componentName)} ` +
        `(expected one of: ${registeredComponentNames().join(", ")})`
    );
  }
  const specJson = JSON.stringify(spec, null, 2);
  if (specJson === undefined) {
    throw new Error(
      `buildAssemblyWrapper: spec for ${componentName} is not JSON-serializable ` +
        `(JSON.stringify returned undefined)`
    );
  }
  const specType = `${componentName}Spec`;

  return `/**
 * Auto-generated by src/ai/assembly-wrapper.ts — do not edit by hand.
 * Assembles the prefab library component "${componentName}" with an inlined spec.
 */

import React from "react";
import { ${componentName} } from "../../../remotion/library";
import type { ${specType} } from "../../../remotion/library";

interface AnimationProps {
  frame: number; durationInFrames: number; width: number; height: number;
  subtitleSafeBottom: number; theme: any; fps: number;
  lineTimings: { startSec: number; endSec: number }[];
}

const SPEC: ${specType} = ${specJson};

const Component: React.FC<AnimationProps> = (props) => (
  <${componentName}
    frame={props.frame}
    durationInFrames={props.durationInFrames}
    width={props.width}
    height={props.height}
    subtitleSafeBottom={props.subtitleSafeBottom}
    theme={props.theme}
    fps={props.fps}
    lineTimings={props.lineTimings}
    spec={SPEC}
  />
);

export default Component;
`;
}
